name: Lint Code Base

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install modules
        run: npm install
        
      - name: Get changed files
        id: changed-files
        run: |
          git diff --name-only > changed_files.txt

      - name: Run ESLint on changed files
        run: |
          CHANGED_FILES=$(cat changed_files.txt | grep -E '\.(js|jsx|ts|tsx)$' || true)
          if [ -n "$CHANGED_FILES" ]; then
            npx eslint $CHANGED_FILES
          else
            echo "No JavaScript or TypeScript files changed."
          fi
